server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ttshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations:
      - classpath:dao/*.xml
      - classpath*:com/**/mapper/*.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    datasource: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    connect-timeout: 30000ms

springfox:
  documentation:
    enabled: true
    open-api:
      enabled: true
    swagger-ui:
      enabled: true

jwt:
  tokenHeader: Authorization
  #  secret: springboot-demo-secret
  expire: 3600
  tokenPrefix: Bearer
