server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ttshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations:
      - classpath:dao/*.xml
      - classpath*:com/**/mapper/*.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher